### ISSUE TITLE
Cadre borning Alert/Feed

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#1]
Je trouve que le cadre "Borning Alert/Feed" prend trop de place sur le "tableau de bord" pour voir ses activités et les classements
--> je mettrai un nouvel onglet sur le site web pour ça
![BC_site_idee#1](https://user-images.githubusercontent.com/110242190/181775770-413e7997-bf72-42e6-a745-53bba75418b0.jpg)

**Comment by briceandre** [comment]
J'ai réécrit la partie responsive du site pour avoir le contrôle de l'emplacement des éléments en fonction de la taille de l'écran.

Du coup, ce que je propose, c'est le layout suivant : 

- Sur un écran large, je garde le layout actuel
- Sur un écran de taille moyenne, le borning-feed est déplacé dans un panel gauche, affiché à la demande de l'utilisateur
- Sur un petit écran (smartphone, etc.), il n'y a plus que la partie centrale qui est affiché. Le menu des challenges part dans un panel droit

Le nouveau site peut être testé à l'adresse : https://test.borning-challenge.be/
