### ISSUE TITLE
Problème distance - arrondi pour les activités manuelles

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#13]
Pour les activités manuelles il y a un souci quand on encode une distance avec une virgule (ou un point, les deux séparateurs sont fonctionnels et c'est top !!)

1) Si j'encode une distance sans écrire directement la valeur arrondie, par exemple 0,300km au lieu de 0,3km le site m'affiche "La distance encodée n'est pas correcte !" 
--> je ne sais pas dans quel cas ce message de distance incorrecte doit s'afficher
--> on devrait pouvoir indiquer 0,300km ou 300m pour la nage si on la bascule en m
--> Si on écrit par contre 0,301 ou 0,31 ou même 0,300001 km le site ne dit rien...

2) Si je prends la nage, si je fais 400m (soit 0,4km) le site m'affiche ensuite 0km et 2 bornes et je ne peux pas sélectionner cette activité pour valider mon #nat300
**--> si possible il faudrait passer la nage en m et pas km et supprimer la case dénivelé (je l'ai mis dans un autre point également)**

3) Si je fais du vélo, vtt ou course, si je fais 5,4km le site m'affiche ensuite 5km et le bon nombre de borne (5,4 pour la course par exemple) et si je fais 5,6 km le site m'affiche 6km et le bon nombre de borne (5,6 pour la course par exemple)
**--> si je veux modifier l'activité, le site me met l'arrondi qu'il a choisi donc si je dis avoir fait 5,6 puis je modifie le site affiche 6km pour l'activité et quand je valide je vois 6km de course et 6 bornes**

**Comment by briceandre** [comment]
La première erreur, c'est un bug : j'ai corigé.
Les 2 autres points, c'est une régression suite à l'encodage des durées des activités. C'est également corrigé
