### ISSUE TITLE
Natation

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#14]
J'ai 2 points d'ajustement sur la natation si possible
- mettre la distance en m et pas en km si possible
- supprimer la case dénivelé (elle est inactive ce qui est déjà bien mais ce serait top de la supprimer carrément si possible)

**Comment by briceandre** [comment]
J'ai supprimé la case dénivelé : c'était une coquille dans le code actuel.
Pour passer de km à m, c'est pas si simple : ça me demanderait de traîter ce champ différemment pour la natation par rapport aux autres. 
Je propose de laisser comme ça pour le moment (de toute façon, s'ils se trompent, il y a le check sur la distance qui va déclencher...). On verra plus tard si on a le temps
