### ISSUE TITLE
Liste challenge 2022 version 2

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#15]
Voilà la nouvelle version des challenges/défis pour 2022
- j'ai mis 3 challenges perfo comme demandé dans un autre sujet
- j'ai rajouté des défis alti
- il faudra vérifier l'encodage des défis woody, squats et shadoks, ils affichent les valeurs de 2019 (100, 2000, 2000) alors qu'ici c'est 25/30/300 --> le compteur lui est juste :)
- j'ai mis la distinction pour les concours H/F quand nécessaire
[Challenges 2022.xlsx](https://github.com/briceandre/BorningChallenge/files/9261963/Challenges.2022.xlsx)

**Comment by briceandre** [comment]
done
