### ISSUE TITLE
Affichage défis

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#16]
Pour les défis libre, si possible il faudrait adapter l'affichage pour tous les classer par catégorie
--> pour fitness il faudrait tout mettre ensemble, les mega et super le sont mais on trouve squat avant les super et le woody en dernier
--> pour les runs, les 1x km sont avant les 5, 7, 8, 9 :(
--> marathon est au milieu est pas avec #run 
--> pour les denivelé, il faudrait trier sur la valeur et pas le nom (Aconcagua qui est l'un des plus haut et Olympe en dernier alors qu'il est "petit" 

Voilà une liste telle que je la verrai, j'ai rajouté une colonne "nom de code" si jamais le site peut trier les défis sur nom de code et pas sur le titre qu'on veut afficher (mais comme un utilisateur peut choisir de trier sur les noms ça va peut être planter)
[Liste défi.xlsx](https://github.com/briceandre/BorningChallenge/files/9262066/Liste.defi.xlsx)

**Comment by briceandre** [comment]
done (sur le site de test... je le mettrai dans le site officiel à la prochaine release...)

**Comment by OlivierDEVOSAlstom** [comment]
Salut Brice
Désolé mais je ré-ouvre l'action pour : 
1) Tu as laissé tous les défis #perfo --> pour moi il n'y en a plus que 3 par sport et il ne faut pas les afficher tout de suite
2) Au niveau des challenges fitness le nom est OK, le compteur est OK mais pas la description
![image](https://user-images.githubusercontent.com/110242190/185303645-344a48ac-e9ec-4a56-a6d7-075d39dbd820.png)

3) J'ai mis à jour la liste avec des nouveaux défis notamment 2 pour dénivelé et 2 pour intermédiaire aux 1000 bornes qu'il faudrait ajouter :)
![image](https://user-images.githubusercontent.com/110242190/185303916-2cddeaf5-62e5-4aff-850a-123a33eb06af.png)

**Comment by briceandre** [comment]
J'ai corrigé le point 2.
Pour les points 1 et 3, je les ferai en même temps que la revue de l'ensemble des défis/concours
