### ISSUE TITLE
Résultats des concours

### ISSUE THREAD

**Issue by briceandre** [briceandre/BorningChallenge#17]
Dans les résultats, je ne vois pas les classements pour les concours... A regarder...

**Comment by briceandre** [comment]
done

**Comment by OlivierDEVOSAlstom** [comment]
L'an dernier on avait fait des concours et donné la possibilité de les battres - ici ce ne sera pas le cas, pour que les gens se battent entre eux et essaient de se dépasser, il faudrait pour moi afficher le classement du concours - on n'afficherait pas les bornes à gagner mais juste un classement. Si quelqu'un fait 100 sauts à la corde et voit qu'en faisait 110 il peut passer premier ça motivera je pense !

**Comment by briceandre** [comment]
Je suis pas sûr de comprendre : il y a bien un classement concours : c'est juste qu'il est pas encore affiché car le premier concours commence semaine prochaine.

Par contre, il permet bien de gagner des points : en 2019, on attribuait 50 bornes au premier, 49 au 2e, etc. J'ai gardé le même principe. 

A voir s'il faut adapter

**Comment by briceandre** [comment]
Du coup, vu que je pense que c'est bon (et que j'essaye de rester sous la barre des 10 open points...), je le ferme. Si besoin, rouvre le ticket
