### ISSUE TITLE
Suivi défis woodywoodpecker/shadok/squatter

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#2]
Ces défis peuvent être validés sans êtres liés à des activités - je propose qu'on puisse remplir un compteur comme on rempli les activités manuellement. Quand le compteur atteint un palier on débloque la validation des défis

Attention, il y a plusieurs niveaux, il faut garder le même compteur sans qu'il ne revienne à 0 après validation d'un défi sinon ça va faire trop. 

Par exemple pour les pompes, on incrémente un compteur sans limite et quand on atteint 300 on peut valider le premier palier, on continue pour atteindre 800 et on valide le deuxième défi et au delà de 1500 on valide le dernier défi et on peut laisser le compte tourner pour ceux qui voudraient suivre le nombre de pompe sur toute la durée du challenge

**Comment by briceandre** [comment]
J'ai changé les activités pour mémoriser la durée, le nombre de squats, de min de planche et de pompes. 
J'ai aussi changé pour que ces éléments ne soient encodables que pour les activités concernées. Pour les squats, planche et pompe, j'ai créé une nouvelle activité : Fitness. Il n'y a que pour cette activité que c'est dispo.
Du coup, les challenges regardent le nombre total de squats/planche/pompe et sont dispo seulement quand le compteur est atteint

**Comment by OlivierDEVOSAlstom** [comment]
J'ai testé, il y a un souci avec squats et pompes, il y a une inversion quelque part.
Si je mets avoir fait 200 pompes l'activité affiche que j'ai fait 200 squats. Et si je veux changer en mettant 200 squats pour faire afficher 200 pompes ça ne fonctionne pas, il faut que je supprime l'activité pour en faire une nouvelle ou que je mette les compteurs de l'activité à 0 avant de remettre d'autres valeurs.

Si possible, il faudrait que le compteur s'affiche quelque part, par exemple à côté du défi
![compteur fitness](https://user-images.githubusercontent.com/110242190/182123091-273e0927-09c7-4c83-ab35-7746944530ad.jpg)

**Comment by briceandre** [comment]
J'ai corrigé le bug qui inversait les valeurs.
J'ai aussi mis le compteur dans les challenges indisponibles (je l'ai fait pour ceux-là, mais aussi pour les challenges d'altitude et pour le mille bornes).
Je trouve que ça serait pas mal du coup d'ajouter d'autres challenges (500 bornes, 1500 bornes, etc.)... Ca motiverait les gens à en faire plus...
