### ISSUE TITLE
Activité vélo électrique/appartement

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#26]
Comme on a décidé de mette le vélo électrique/appartement comme une activité à part entière avec une conversion différente du vélo, il faut ajouter une nouvelle activité possible !

Il faut créer l'activité Vélo électrique/appartement avec une conversion à 50km = 10 bornes - je ne mettrais pas de dénivelé

**Comment by briceandre** [comment]
done (mais pas encore complet sur le site de test.... Sera mis en ligne avec la prochaine relese...)
