### ISSUE TITLE
Affichage FR

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#27]
Encore du cosmétique !

Quand on a le site en français, pour aller sur les menus des résultats on se retrouve avec les noms en anglais...
Si possible on devrait les mettre en français :) Je peux même t'aider à traduire ^^
<img width="686" alt="Menu FR" src="https://user-images.githubusercontent.com/110242190/184889581-5b792761-51d6-4cde-a26c-4820f0c0ea38.png">

**Comment by briceandre** [comment]
corrigé
