### ISSUE TITLE
Message Not Defined

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#29]
Quand on se connecte au site (après avoir rentrée mail + mdp), le message "Not Defined" apparait
A voir si possible de le supprimer

![image](https://user-images.githubusercontent.com/110242190/186115952-ea834f95-f215-47d1-a8ab-464fe4befe54.png)

**Comment by briceandre** [comment]
C'est pas un bug : j'attends toujours la liste des pages à afficher chaque semaine :-)
