### ISSUE TITLE
Commentaires sur les activités

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#3]
Quand on regarde ses activités ou celles des autres il est possible d'ajouter des commentaires
Je ne sais pas si ça a beaucoup été utilisé, si "non" on peut supprimer mais si "oui" alors il faudrait améliorer le système
![Uploading BC_site_idee#2.jpg…]()

**Comment by briceandre** [comment]
Ca n'existait pas est 2019. 
En 2020, on a ajouté les borning feed, et la possibilité de commenter les activités des autres. Vu qu'en 2020, il n'y a pas eu beaucoup de participation, on verra cette année si c'est utilisé.
Ta capture d'écran ne passe pas. Que souhaites-tu améliorer ?

**Comment by OlivierDEVOSAlstom** [comment]
Je retente la capture d'écran ! Je voulais améliorer la façon d'ajouter un commentaire, pour moi il manquerait un bouton pour "valider" le commentaire, soit écrire "appuyer sur entrée pour valider le commentaire" soit un bouton "valider"

![BC_site_idee#2](https://user-images.githubusercontent.com/110242190/182106442-a46421b0-b22b-4625-b81c-5edeb4a6b68d.jpg)

**Comment by briceandre** [comment]
J'ai fait la plupart des modifs. 
Par contre, je n'ai pas ajouté la possibilité de mettre un commentaire dans l'encodage des commentaires. Le but du commentaire, c'est de permettre à une autre personne de commenter l'activité (et à celui qui a fait l'activité de répondre au commentaire). Du coup, je ne vois pas bien le but de mettre un commentaire en créant l'activité.
L'idée, c'est : 

- tu fais une activité
- les autres la voient dans le "borning news". S'ils veulent, ils peuvent ajouter un commentaire
- Si un commentaire est mis sur ton activité, tu le vois dans ton "borning feed", et tu peux éventuellement y répondre.

A rediscuter et voir s'il faut améliorer le système...

**Comment by OlivierDEVOSAlstom** [comment]
C'est clair !
Pour moi on peut toujours supprimer le borning feed/alert (à discuter) et pour les commentaires je vois que tu as ajouté un petit bouton pour valider (et ne pas faire entrée) donc c'est parfait pour moi :)
