### ISSUE TITLE
Interligne page (CKE editor)

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#32]
Mettre l'interligne à 0 (CSS ?)

**Comment by briceandre** [comment]
Ca n'a pas l'air de s'afficher mal chez moi ?

![image](https://user-images.githubusercontent.com/21170059/188274190-9edbdc0b-d4f7-4917-9199-07c64d4a7186.png)

**Comment by OlivierDEVOSAlstom** [comment]
Il reste des espaces que je n'ai pas voulus :(
Ca devrait plutôt donner ça 
![image](https://user-images.githubusercontent.com/110242190/188309557-0b8f7b22-0cbf-4c25-93cb-6ae61c00203e.png)

**Comment by briceandre** [comment]
Comme discuter : entrer les retours à la ligne en maintenant la touche majuscule appuyée
