### ISSUE TITLE
Challenge #prendredelahauteur

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#33]
Cette semaine le challenge à relever et prendre de la hauteur, on est sensé cumuler sur la semaine 200m de D+ (normalement avec des activité de 5bornes minimum, au pire si c'est pas dans le calcul ce n'est pas trop grave)

Ici j'ai rentré marche sportive 15km et 201m mais je ne peux pas valider le challenge.
J'ai le même souci si je fais course ou VTT. Et si je fais 2001m ça ne va pas non plus

Tu pourrais revoir les conditions d'acceptation du challenge ?

**Comment by briceandre** [comment]
Le challenge n'est pas encore implémenté...C'est pour ça qu'il marche pas.
J'ai tout implémenté jusqu'à semaine 6 inclue... Ca laisse de la marge.
J'ouvre un ticket dédié pour faire le suivi des challenges à encore coder
