### ISSUE TITLE
Challenges à coder

### ISSUE THREAD

**Issue by briceandre** [briceandre/BorningChallenge#34]
Statut actuel : 
https://alstomgroup-my.sharepoint.com/:x:/p/brice_andre/ERgzDXzujHJGs2Uiyz40yPcB4qCKR_3kkSI1yH7nq826Nw?e=Q6SB45

On a jusque fin de semaine 6...

**Comment by OlivierDEVOSAlstom** [comment]
Il faut que tu me redises ce que tu attends car ce n'est plus clair dans ma p'tit tête
