### ISSUE TITLE
Tags dans page pour résultats automatiques

### ISSUE THREAD

**Issue by briceandre** [briceandre/BorningChallenge#36]
Ajouter un mécanisme qui permet de compléter la page d'accueil avec les noms des maillots et des équipes qui ont gagné

**Comment by briceandre** [comment]
done

**Comment by OlivierDEVOSAlstom** [comment]
Truc de dingue, ça marche du feu de Dieu, bien joué !!
Je me note les codes ici au cas où je sois suffisamment doué pour les casser

 ||total_nb_borns|| bornes !!
 ||pink_jersey|| remporte le maillot rose avec ||pink_jersey_value|| bornes
||yellow_jersey|| reporte le maillot jaune avec(||yellow_jersey_value|| bornes
||polkadot_jersey|| remporte le maillot à point avec ses ||polkadot_jersey_value||  bornes D+
L'équipe ||team_week|| arrive en tête avec ||team_week_value|| bornes, ses membres porteront la casquette d'or 
Total courses : ||nb_run_walk_week|| km
Total natation : ||nb_swim_week|| km
Total vélo : ||nb_bike_week|| km
Total heures de sport : ||nb_hours_sport||
