### ISSUE TITLE
Réorganisation de la page d'accueil

### ISSUE THREAD

**Issue by briceandre** [briceandre/BorningChallenge#37]
- faire en sorte qu'en rechargement de page, ce soit la page de présentation du challenge qui s'affiche
- Ajouter un menu "infos de la semaine"
- Déplacer le menu "tableau de bord" à droite

**Comment by briceandre** [comment]
done

**Comment by OlivierDEVOSAlstom** [comment]
Le site devient vraiment magnifique !! Par contre j'ai 2 remarques
1) On ne voit toujours pas qu'en cliquant sur "Let's Born again" on revient sur la page "Info de la semaine" - ça ne dérange pas, à voir si on supprime le lien ou si on met une petite main pour montrer qu'on peut le sélectionner

2)Tu as écris "Mes Pefs", je ne sais pas si c'est voulu mes j'aurais plutôt écrit "Mes Perfs"

![image](https://user-images.githubusercontent.com/110242190/189494547-f9f69743-17f4-4011-9bcc-cf566c858887.png)

**Comment by briceandre** [comment]
Les deux points sont corrigés (dans la version de dev). Je mettrai la correction en ligne d'ici fin du weeken
