### ISSUE TITLE
Cosmétiques affichage

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#4]
Au niveau de la liste des activités j'aimerais bien qu'on modifie : 
1) Ajout de la date devant l'activité, ainsi on voit qu'on n'a pas fait 2 activités le même jour à la même heure et quand on fait des challenges d'équipe sur la semaine, on peut vérifier qu'on a bien le nombre de jour nécessaire (si par exemple on doit faire 5 bornes 3 jours de suite)
2) Au niveau de l'heure s'il est 16h03, le site affiche 16h3, ce serait plus joli de garder 16h03
3) Au niveau des activités, même si on voit le type d'activité je pense qu'on pourrait rajouter le code couleur qui est utilisé dans le tableau "statistique"

![BC_site_idee#3](https://user-images.githubusercontent.com/110242190/181781523-5f5ac651-482a-4719-a0b6-760161be9987.jpg)

**Comment by briceandre** [comment]
Pour les dates et les heures, c'est fait.
Pour la couleur, à discuter... D'une part, je ne choisis pas la couleur dans les graphes (c'est google charts qui les alloue, même si c'est vrai que je pourrais les forcer). D'autre part, je n'ai pas compris si le but était de mettre la couleur de texte, ou l'arrière plan. Dans tous les cas, il faudrait des couleurs qui vont bien...
A discuter...
