### ISSUE TITLE
Résultat Ultimate

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#40]
En parcourant les différents classements je suis tombé là dessus
--> je pense qu'il y a un petit souci sur le calcul ;)

![image](https://user-images.githubusercontent.com/110242190/188799216-81dfb668-ec07-45b6-a863-f30cfe9d891c.png)

**Comment by briceandre** [comment]
Je pense que c'est bon : le classement ultimate, c'est la somme des positions des classements run/swim/bike. 166, ça doit être la somme des classements de ceux qui n'ont pas encore fait d'activité

**Comment by OlivierDEVOSAlstom** [comment]
Comme discuté c'est OK au niveau calcul, il faudra qu'on mette le règlement à jour pour que ce soit plus clair

Par contre comme discuté, il faudrait inverser le classement, qu'on voit du meilleur au dernier et non l'inverse

**Comment by briceandre** [comment]
Corrigé (sur le site principal)
