### ISSUE TITLE
Affichage site 

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#41]
Au niveau du site, pour éviter de se retrouver avec des pages blanches quand on se connecte je propose
- créer un onglet "Information de la semaine" où l'on affichera de base les "pages" sur lesquelles on écrira les défis de la semaine (+ résultats de la semaine passée)
- Sous l'onglet activité ou dans un menu à gauche, pouvoir directement accéder à ses performances (= quand on clique sur son nom dans le classement) et à celles de son équipe

Pour les menus en haut, mettre si possible dans l'ordre (de gauche à droite) 
Information de la semaine // Activités // Tableau de bord

**Comment by briceandre** [comment]
done
