### ISSUE TITLE
Affichage des résultats - modification classement

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#45]
Comme discuté en réunion avec Lise et indiqué ensuite sur teams, on ré-intègre les bonus 20 bornes des défis réalisés pour l'obtention des maillots (ce que tu as déjà encodé)

Par contre, ça reste intéressant de voir la perfo pure ! Chacun le voit dans son compteur mille borne mais il faudrait le rendre visible pour tout le monde (ça valorise notamment ceux qui font du sport type crossfit ou football et qui n'ont eux pas moyen d'engrenger de points bonus).

Du coup ce que je propose, que ce soit pour le classement individuel ou équipe
- Classement semaine : on voit uniquement la perfo pure, avec D+ mais sans bonus défis libre ou équipe
1) Classement de la semaine x : toutes les bornes de la semaine x
2) Classement de la semaine en cours : toutes les bornes de la semaine en cours
3) Nouveau : Classement "Depuis le début du Borning" : cumul de toutes les bornes des semaines précédentes + semaine en cours

- Classement scratch : on voit tout, perfo + D+ + défis libre + défis équipe
1) Classement de la semaine x : toutes les bornes de la semaine x
2) Classement de la semaine en cours : toutes les bornes de la semaine en cours
3) Nouveau : Classement "Depuis le début du Borning" : cumul de toutes les bornes des semaines précédentes + semaine en cours

J'espère que c'est juste "un peu de codage" et rien d'insurmontable ! 
Et si ce n'est pas clair fais moi signe :)

**Comment by briceandre** [comment]
Je vois ce que tu veux faire, et non, ce n'est pas très difficile à implémenter.

Par contre, je ne comprends pas l'agencement des menus que tu proposes. Et si on fait des classements avec/sans défis, il faut que ce soit vraiment très clair pour tout le monde.

ce qui me perturbe ci-dessus, c'est que, dans ce que tu as appelé "classement semaine", le dernier onglet est "depuis le début du borning".... Du coup, je suis perdu.

Je proposerais de faire un classement de la semaine avec et sans les défis, et un classement scratch avec et sans les défis. Reste par contre à leur trouver un nom, et voir comment on organise tous les classements pour pas perdre tout le monde.

Bref, si tu pouvais proposer la structure exacte du menu, avec les noms exacts qu'on affiche, et les règles de calcul pour chaque catégorié, je devrais pouvoir faire ça pour que ce soit déjà présent lundi matin

**Comment by OlivierDEVOSAlstom** [comment]
Voilà 2 images si ça peut t'aider à comprendre. 
Pour moi entre semaine et scratch ça doit juste être une différence sur le comptage des bornes de D+ et défis

![Classement semaine](https://user-images.githubusercontent.com/110242190/189535713-93a314ef-b4ca-491f-844d-6c01ffa40417.jpg)
![Classement scratch](https://user-images.githubusercontent.com/110242190/189535717-7db5baaa-04b5-4a75-9639-d5a5c50d0644.jpg)


Je pense que je t'ai "perturbé" c'est que pour toi le scracth = from scratch = depuis le début

Je pense que ma proposition est plus simple à mettre en oeuvre 

Sinon, si tu es capable facilement de faire un bouton "avec Defis et D+" qui mettrait automatique à jour le taleau on peut le faire voir

**Comment by briceandre** [comment]
Je propose qu'on se prenne 5-10 minutes pour en parler ensemble. 
Je vais pas le faire pour cette semaine : on va regarder ça et je le ferai calmement après

**Comment by briceandre** [comment]
Pas de nouvelles, ça date d'il y a 2 ans... Je clôture
