### ISSUE TITLE
Ajouter photos (+autres ?) sur le site Borning Challenge

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#46]
Pour ceux qui ont des comptes Strava, normalement on a dit qu'ils pouvaient mettre les photos de leur challenge (reporter, sauverparlegong) sur Strava. Et même moi qui n'ai pas Strava je vois les photos donc c'est parfait !

Par contre, pour ceux qui n'ont pas Strava mais qui voudraient rajouter des photos de leurs sorties (voir les fichier gpx ? Moi j'utilise OpenRunner car gratuitement je peux me préparer des parcours :P) je me dis qu'en plus de les mettre sur Teams on pourrait les ajouter sur le site ?

Pour moi on va bourrer le site si on imagine qu'il y aura 50 personnes qui vont en moyenne mettre 20 photos de 5Mo (5 Go) 
1) La solution la plus simple serait de demander à chacun de réduire la taille des photos (via par exemple IrfanView qui est un logiciel proposé dans l'AlstomStore)
2) Sinon il faudrait que l'outil soit intégrer dans le site et permette une réduction automatique sur le site ?
3) Il faudrait sinon que les modérateurs puissent accéder aux fichiers et les réduire eux même 

C'est vraiment une proposition comme ça, si on ne peut pas il ne faut pas qu'on se l'impose, Teams sera là ;)

**Comment by briceandre** [comment]
http://jsfiddle.net/eGjak/234/

**Comment by briceandre** [comment]
on garde teams pour les photos
