### ISSUE TITLE
Defi alti

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#47]

**Comment by OlivierDEVOSAlstom** [comment]
Pour les 4 défis alti500, alti1000, alti1500 et alti2000, il faut les valider avec 4 activités. Une sortie de 3000m ne doit pas permettre de valider les 4 défis - et comme pour la course, vélo ou natation il faudra les débloquer dans l'ordre

**Comment by briceandre** [comment]
SELECT (select email FROM "user" WHERE "user".user_id=defi.user_id) as user, (SELECT name_fr FROM existing_defi_type e WHERE e.defi_type_id=defi.defi_type_id), activity_id, (SELECT count (defi_id) FROM defi_activity_link al WHERE al.activity_id=l.activity_id AND defi_id IN (SELECT defi_id FROM defi WHERE defi_type_id IN (SELECT defi_type_id FROM "public"."existing_defi_type" WHERE sorting_data ILIKE '10_deniv_%'))) FROM defi LEFT JOIN defi_activity_link l ON defi.defi_id=l.defi_id WHERE challenge_id=7 AND defi_type_id IN (SELECT defi_type_id FROM "public"."existing_defi_type" WHERE sorting_data ILIKE '10_deniv_%') ORDER BY activity_id;

**Comment by briceandre** [comment]
done
