### ISSUE TITLE
Connexion impossible seveur --> serveur

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#48]
Un petit problème simple à corriger : en voulant me connecter ce matin j'ai un message d'erreur
En le lisant je me rends compte qu'il est écrit "seveur" au lieu de "serveur" ;)

![image](https://user-images.githubusercontent.com/110242190/191894673-52e6d51b-405a-4b80-ba69-264d3fe7d24e.png)

**Comment by briceandre** [comment]
corrigé
