### ISSUE TITLE
Message d'alerte en cas de rentrée manuelle erronée

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#5]
Pour les activités encodées manuellement, il faut voir si ce serait compliqué de mettre des alertes. J'ai mis par exemple dans le règlement qu'il faudrait mettre la natation en mètre et pas en km (car il y avait eu quelques erreurs l'an dernier). Si par exemple on tape 1000km de vélo au lieu de 100km on pourrait mettre un message d'erreur

![BC_site_idee#4](https://user-images.githubusercontent.com/110242190/181781812-bd92912b-ff7c-4d46-866b-bfde3cd74914.jpg)

**Comment by briceandre** [comment]
Vu que, maintenant, on encode les durées des activités, je calcule la vitesse moyenne de l'activité. Je mets un warning si on dépasse les vitesses moyennes suivantes : 

- càp : 20km/h
- vélo/vtt : 50km/h
- natation : 10km/h
- marche sportive = 8km/h

**Comment by OlivierDEVOSAlstom** [comment]
Excellent pour les warning sur la vitesse moyenne, ça marche au top :)
Mais je pense que tu pourrais encoder d'autres warning pour les distances durée comme par exemple

cap/marche : 70km
vélo/VTT : 300 km
natation : 10km
sport doux/intense : 240min
dénivelé D+ : 5000m (sans distinction de l'activité)

**Comment by briceandre** [comment]
done

**Comment by OlivierDEVOSAlstom** [comment]
Ca fonctionne sauf pour 2 points : 
1) La limite natation semble être fixée à 15km et non 10km
2) Il n'y a pas de limite sur le dénivelé D+ (je peux faire 200000m si je veux...)

**Comment by briceandre** [comment]
done

**Comment by OlivierDEVOSAlstom** [comment]
J'ai ré-ouvert le point pour 2 remarques
1) Seul une limite s'affiche, si je cours 100km pendant 1min avec 10000m de dénivelé il va juste me dire que j'ai couru à 6000km/h mais rien sur la distance ou dénivelé
 --> on devrait rarement abuser sur 2 limites en même temps mais à voir si c'est possible/facile de mettre une alerte si on dépasse plusieurs limites 
2) quand on participe au concours natation, on peut indiquer qu'on a nagé 1sec ou 200m, peut être même des limites sur les concours aussi ? Genre 150 pompes, les recors européen en natation/course, et 5min de chaise ?

**Comment by briceandre** [comment]
J'ai modifié pour avoir l'ensemble des limites.

Par contre, pour l'avoir sur les concours, c'est plus compliqué... Je propose de mettre ça de côté pour le moment et de voir plus tard
