### ISSUE TITLE
Ajout minimum marche sportive

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#53]

**Comment by OlivierDEVOSAlstom** [comment]
Pour pouvoir ajouter une activité marche sportive, il faut que l'activité réalisée soit supérieur ou égal à 2km 
Une activité de 500m (parking --> bureau) ne pourra ainsi pas être considérée

**Comment by briceandre** [comment]
fait (sur site de dev). Sera mis sur site officiel avant le début du challenge

**Comment by OlivierDEVOSAlstom** [comment]
Il y a bien un minimum de 2km, ça fonctionne nickel

**MAIS** sur la version anglaise le message d'avertissement parle de daily walk et non pas de sport walk
![image](https://github.com/briceandre/BorningChallenge/assets/110242190/ec580ccd-89a6-4d36-a47f-77dbe718aa2b)
Il faut corriger le nom dans le message d'avertissement

**Comment by briceandre** [comment]
done (sur site dev). Sera mis sur site principal d'ici ce soir
