### ISSUE TITLE
Ajout d'une nouvelle activité "Gravel"

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#55]
Il faut créer une activité "Gravel"
Les infos sont :
Activité type "VTT/Vélo" donc à encoder avec nom, date, heure, distance, durée et élévation
Distance : 33km = 10 bornes
Elevation : 330m de D+ = 1 borne
Une activité "gravel" permet de valider les défis vélos (hors défi #megaroute)

**Comment by briceandre** [comment]
fait (sur site dev)

**Comment by OlivierDEVOSAlstom** [comment]
L'activité est bien créée, la définition des bornes est correcte (33 km = 10 bornes et 330m D+ = 1 borne) et je peux valider un défi #vélo avec :)

**MAIS** si je fais du dénivelé en gravel je ne peux pas débloquer les défis #alti et ça ne compte pas pour le D+ cumuler pour les défis comme #Botrange . Je pense également que le Gravel ne permet pas de débloquer les défis d'équipe, si je fais 3 activité gravel je ne peux pas débloquer le #gogogo par contre avec 3 courses oui

**Comment by briceandre** [comment]
done (sur site de dev... Je le mets sur test et site officiel d'ici ce soir)
