### ISSUE TITLE
Creation d'un maillot du plus combatif

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#56]
A VOIR SI POSSIBLE A FAIRE // Sinon je le fais à la main

Afin de mettre en afin d'autres personnes que ceux qui glanent toujours les maillots jaunes ou rose, l'idée serait de créer un nouveau maillot du plus combatif (un pour les hommes, un pour les femmes).
Pour l'attribution, l'idée est de partir du classement est de le donner la première personne non déjà récompensée

1) En première semaine, ce serait donc le 2eme homme et la 2eme fille
2) En semaine x, ce serait le premier homme/fille qui n'aurait jamais eu le maillot jaune/rose ou un maillot du plus combatif
--> ca peut être le deuxième du classement mais ça pourrait aussi être le 7eme si les 4 premiers ont déjà eu le maillot jaune et si les 5-6 ont déjà eu le maillot du plus combatif

--> c'est uniquement un titre honorifique, ce maillot ne rapporte aucun point

**Comment by briceandre** [comment]
Pour finir, c'est géré à la main
