### ISSUE TITLE
Libérer tous les défis personnels - pas de progression

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#57]
Contrairement à 2022 où on a mis en place une progression (pas possible de valider le #run10 si #run5 et #run7 non validés avant) on va rendre accessible tous les défis qui peuvent être validés avec une activité
--> Si on court 10km, on peut valider #run5 ou #run7 ou "run10

**Comment by briceandre** [comment]
modifié (sur site dev). Sera mis en ligne avant début du challenge

**Comment by OlivierDEVOSAlstom** [comment]
Je te laisse vérifier mais visiblement il y a un souci avec les défis#alti

Si je fais 2000m de dénivelé le site ne me propose que le #alti100 à valider mais pas les autres --> j'ai l'impression qu'il y a encore l'idée de progression sur ces défis

**Comment by briceandre** [comment]
En effet, il y avait une limitation qui imposait de faire les défis dans l'ordre. J'avais oublié qu'on avait ça aussi sur ces défis là.
J'ai enlevé la limitation (sur site de dev). Je le mettrai en ligne dès que j'aurai fait les dernières modifs
