### ISSUE TITLE
Défis 2023 vs defis 2022

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#59]
Voilà ici le fichier avec le comparatif des defis 2023 vs ceux de 2022
Il y a peu de changement par contre pas mal de nouveau

[Challenges 2023 vs 2022.xlsx](https://github.com/briceandre/BorningChallenge/files/11856017/Challenges.2023.vs.2022.xlsx)

**Comment by briceandre** [comment]
J'ai tout mis à jour, sauf les défis doux et intensifs. Ceux-là, ce sera pour demain

**Comment by briceandre** [comment]
done

**Comment by OlivierDEVOSAlstom** [comment]
Il y a 2 défis non correct
1) Etna a remplacé Aneto, le compteur est visiblement bon mais il faut changer le nom du défi + définition du défi (3357m au lieu de 3404) - c'est moi qui me suis planté dans mon fichier, j'ai coché "identique à l'an dernier" et "changement"
![image](https://github.com/briceandre/BorningChallenge/assets/110242190/a96c8449-e0ff-4262-a044-9418bf44d55c)
2) Le challenge endurant c'est de borner pendant 6 semaines d'affilé et non pas 10 semaines --> il faut changer la définition du défi et vérifier si le code est correct

**Comment by briceandre** [comment]
done

**Comment by OlivierDEVOSAlstom** [comment]
Je n'ai peut être pas été assez claire mais
1) Il faut changer le nom du défi, il doit s'appeler #Etna et non pas #Aneto // par contre la valeur a bien changé :)
![image](https://github.com/briceandre/BorningChallenge/assets/110242190/01302e72-61db-4e6f-8fc8-6f9072b234f6)


2)Il est toujours marqué pour le défi "endurant" qu'il faut le faire 10 semaines d'affilé et non pas 6
![image](https://github.com/briceandre/BorningChallenge/assets/110242190/134574ae-f6cd-49d7-aeb4-8b2d2b840ae2)

**Comment by briceandre** [comment]
Done
