### ISSUE TITLE
Traduction Anglais et Néerlandais

### ISSUE THREAD

**Issue by briceandre** [briceandre/BorningChallenge#6]

**Comment by briceandre** [comment]
done

**Comment by OlivierDEVOSAlstom** [comment]
Juste une remarque : pour l'anglais, quand on veut supprimer une activité c'est "SUPPRESS" qui est affiché, pour moi la meilleure traduction serait plutôt "DELETE"

Pour le NL je n'ai pas encore vu la possibilité de l'avoir, scinder l'activité en 2 pour valider EN et laisser ouvert NL ?

**Comment by briceandre** [comment]
Pour ajouter le néerlandais, il me faut quelqu'un pour traduire les fichiers de langue :-)

J'en avais parlé à Pierre qui m'a dit qu'il allait y regarder...

Entretemps, je ferme le ticket pour qu'il reste pas dans ma todo list. Mais dès que vous avez quelqu'un pour traduire, tu peux rouvrir
