### ISSUE TITLE
Renommer activité velo --> vélo route

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#60]
Hello Brice
Pour coller un peu plus au règlement, je propose de renommer l'activité "vélo" en "vélo route" comme ça je pense qu'on est bien claire et carré sur les 4 activités vélo possible (VTT, Gravel, Vélo route et vélo électrique) 

Pour l'anglais aussi il faudrait changer ce qui donne "Road bike" au lieu de "Bike"

**Comment by briceandre** [comment]
done
