### ISSUE TITLE
Accès admin - Pages / Team / Users

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#62]
Salut Brice,

J'ai l'impression que par rapport à l'an dernier tu m'as ajouté comme admin pour les équipes et les personnes. Je suis prêt à monter en responsabilité si c'est ton envie ;) Par contre quand je clique sur "users" je me retrouve sur la définition des pages mais pas des participants :( Donc s'il y a un souci avec un participant pour l'instant je ne peux pas t'aider...

Il y a un moyen aussi de changer le nom des équipes ? Si jamais ceux qui s'appellent equipe 1 ou equipe 2 souhaitent changer

**Comment by briceandre** [comment]
J'ai pas encore codé la partie users :-) Je te donnerai accès à la page dès que je l'aura faite
Pour les teams, y a pas encore moyen de changer le nom, mais c'est bien le but de pouvoir le faire également

**Comment by briceandre** [comment]
dupliqué d'un autre ticket
