### ISSUE TITLE
Modification mail d'une personne déjà inscrite 

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#63]
2 bugs : 

- email avec tabulation devant est accepté et crée un nouveau compte
- email qui existe déjà sur un autre compte est rejeté, mais l'utilisateur est pas prévenu

**Comment by OlivierDEVOSAlstom** [comment]
Sébastien Poulain a aussi un souci (et pour qui j'avais voulu changer l'adresse mail), pourrais tu regarder pour basculer de l'adresse [sebastien.poulain-ext@alstomgroup.com](mailto:sebastien.poulain-ext@alstomgroup.com)  à l'adresse [sebastien.poulain@alstomgroup.com](mailto:sebastien.poulain@alstomgroup.com)

**Comment by OlivierDEVOSAlstom** [comment]
Souci également avec Raphael CHARLIER, visiblement le site ne voit pas l'adresse correcte, il n'a pas accès à l'édition 2023
à vérifier si son adresse mail : raphael.charlier@alstomgroup.com est correctement enregistrée

**Comment by OlivierDEVOSAlstom** [comment]
Une personne a mal encodé son adresse mail, elle est encodée comme jordane.crelot@alsomgroup.com alors que la bonne adresse mail est jordane.crelot-ext@alstomgroup.com

**Comment by briceandre** [comment]
done. Ils doivent demander un nouveau mot de passe

**Comment by OlivierDEVOSAlstom** [comment]
Laurent MARGUET a 2 comptes, garder le compte avec l'adresse ALSTOM et supprimer le compte perso (adresse Orange)

**Comment by OlivierDEVOSAlstom** [comment]
RECOURSE Kylian a aussi 2 comptes, il va utiliser son compte avec l'adresse ALSTOM, on peut supprimer son autre compte avec son adresse perso
