### ISSUE TITLE
Concours - supprimer point

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#70]
Je pense qu'on n'a toujours pas atterri sur le comptage des points du concours, ici je vois que le site affiche 50 pour le premier et une borne de moins à chaque participant mais sur Teams avec Lise on voulait mettre 30 points au premier, 1 au dernier, et faire un incrément en fonction du nombre de participants 

Pour moi il faut supprimer l'affichage des points sur le site et ne pas les compter dans les points perso/équipe
--> On va rediscuter du nombre de point attribués et seulement les distribuer à la fin des 13 semaines

**Comment by briceandre** [comment]
Je pense que c'est plus d'actualité
