### ISSUE TITLE
Activités semaine 4

### ISSUE THREAD

**Issue by OlivierDEVOSAlstom** [briceandre/BorningChallenge#72]
Défi d'équipe
#DrawTheBorning

Explication FR
Au moins 4 membres de l'équipe doivent réussir à écrire ensemble le mot BORNING durant leurs sorties (marche/course/vélo). Chacun doit dessiner au moins une lettre et activité de 5 bornes minimum. Vous pouvez transmettre vos photos de sorties ou votre trace Strava

Explication EN
At least 4 members of the team have to draw the word BORNING during there activites (walk/run/bike). Each member has to draw at least 1 letter with an activity of 5 bornes minimum. You can share you picture of Strava trace.

Concours
Twister

(même que l'an dernier)

**Comment by briceandre** [comment]
Fait (avec bcp de retard... Sorry...)
