### ISSUE TITLE
Pop-Up "nouveau défi à valider" 

### ISSUE THREAD

**Issue by LiseBorning** [briceandre/BorningChallenge#79]
Le créer et vérifier si on peut avoir 1) un bouton OK pour valider directement et si pas 2)un lien vers la page pour validation

(valider le défi le plus haut possible disponible)

**Comment by briceandre** [comment]
C'est fait : en cas d'ajout d'une activité qui libère un défi, il y a un popup pour prévenir qu'un défi est dispo, et qui propose d'aller à la page d'encodage du défi
