### ISSUE TITLE
Révision des bornes concours

### ISSUE THREAD

**Issue by LiseBorning** [briceandre/BorningChallenge#80]
max 30 bornes, diviser par le nombre de participants

**Comment by briceandre** [comment]
je suis pas sûr d'avoir compris... S'il y a 50 participants:

- le 1er a 30
- le 2e a 29,4
- le 3e a 28,8
- etc ?

Si oui, on n'a jamais travaillé avec décimales. Du coup, je fais quoi ? J'arrondis au plus proche ? Au plus bas ?

**Comment by LiseBorning** [comment]
Est-il possible d'ajouter une décimale à l'arrondi supérieur? 
(si on est 13 participants, le premier aurait 30 points et le 2eme 27,7692307692308 --> mieux d'afficher 27,8)
Si pas possible on précisera que le site prend en compte les décimales mais ne les affiche pas (c'est bien le cas? ) et que les personnes sont bien classées dans l'ordre.

**Comment by briceandre** [comment]
done
