### ISSUE TITLE
Algorithme de sélection des activités

### ISSUE THREAD

**Issue by LiseBorning** [briceandre/BorningChallenge#81]
Partager l'algorithme de sélection des activités visibles en pop-up (pour ne pas voir que les gens de son équipe)

**Comment by briceandre** [comment]
score = nombre de bornes de l'activité
          + 50 si l'utilisateur a au moins été une fois dans l'équipe de cette personne dans une des éditions du challenge
          + 2*nombre de commentaires mis sur les activités de l'utilisateur
Les activités qui ont le plus haut score sont sélectionnées
on ne sélectionne que les activités dans une certaine fenêtre de temps

**Comment by LiseBorning** [comment]
j'ai proposé score= 2*nombre de bornes + 20 si utilisateur équipe et on peut laisser comme ça les commentaires
à voir si les autres sont ok :)

**Comment by briceandre** [comment]
done
