### ISSUE TITLE
Nombre de bornes des défis personnels et validation

### ISSUE THREAD

**Issue by LiseBorning** [briceandre/BorningChallenge#84]
La réalisation de défi personnel est désormais de 10 bornes au lieu de 20 bornes.
Les défis d'équipe restent à 20bornes. 
Maximum de 5 défis personnels validables le samedi, max de 5 le dimanche, les autres jours de la semaine pas de limitation: sont exceptés à cette règle les défis alti de dénivelé et les défis fitness : squat, pompe, planche

**Comment by briceandre** [comment]
C'est fait.
Par contre, je n'ai pas mis d'exceptions sur les alti-dénivelés-fitness : c'est plus compliqué à faire. On verra à l'usage si c'est nécessaire.
