### ISSUE TITLE
Communication challenges d'équipe

### ISSUE THREAD

**Issue by LiseBorning** [briceandre/BorningChallenge#85]
•	Planning global des challenges d’équipes dès le début du borning challenge
•	Garder un rappel à la semaine
•	Ajouter les bornes à gagner pour chaque défi

**Comment by briceandre** [comment]
De ma compréhension, il n'y a que le 3e point qui nécessite un changement sur le site, avec une adaptation du nombre de bornes de chaque défi. Est-ce exact ?

Si oui, il me faudrait la liste des défis et les bornes de chacun d'eux pour que je puisse faire cette adaptation

**Comment by LiseBorning** [comment]
[Challenges2024 (1).xlsx](https://github.com/user-attachments/files/15725456/Challenges2024.1.xlsx)
voilà le planning

**Comment by briceandre** [comment]
done
