### ISSUE TITLE
Liste des défis 2024

### ISSUE THREAD

**Issue by briceandre** [briceandre/BorningChallenge#86]
[Challenges2024.xlsx](https://github.com/user-attachments/files/15638223/Challenges2024.xlsx)

**Comment by LiseBorning** [comment]
Changement sur le défi de la semaine 6: 
On a toujours les 7 catégories. Au lieu d'avoir un défi validable sur la semaine on en aurait 7.
Quand une activité de min.5 bornes est disponible, la personne peut valider un des 7 défis de la semaine avec (peu importe le jour) et ça lui rajoute 5 bornes supplémentaires par catégorie validée (il faut faire confiance aux gens qu'ils ont bien fait un sport correspondant)
Le défi de la semaine pour le valider c'est de valider au moins 3 catégories, dans ce cas on remporte le challenge de la semaine qui nous rajoute 5 bornes en plus (donc au total 3x5 bornes des catégories + 5 bornes de la semaine =20 bornes défi validé). 
Il restera 4 catégories à valider pour 5 bornes chacunes en bonus (donc sur la semaine possibilité de remporter 7X5+5=40 bornes individuelles avec 7 activités de 5 bornes)
Si au moins 4 membres valident 3 catégories sur la semaine l'équipe remportent 4x20 bornes= 80
5 membres 5x20+10=110; 6 membres 6x20+20=140 bornes

Les catégories: Catégorie aquatique/nautique exemple : natation, kayak, aviron, fitness en piscine
Catégorie Musculation/Fitness : haltérophilie, circuit training , crossfit
Catégorie athlétisme/cyclisme : course, lancers, marche, sauts, épreuves combinés
Catégorie sport individuel : escalade, sports de tir (tir à l’arc) sports équestres, golf
Catégorie sport d’équipe : sports de ballon (basket, football, handball, rugby, volley), raquette en double
Catégorie 1 contre 1 : sports de combats, sport de raquette (badminton, tennis, tennis de table), escrime
Catégorie sport artistique,gymnique, danse, pilate, yoga, callisthénie.

**Comment by LiseBorning** [comment]
Demande pour défi d'équipe semaine 10 sur les pools de 4 équipes:
Est il possible d'adapter la page d'accueil du site avec le classement en temps réel des pools sous forme de tableaux? 
Mon idée: si 320 participants, ça donne 80 pools. On fait un tableau de 4 colonnes et 20 lignes
Dans chaque cellule, le nom des 4 équipes de la pool avec leur score en bornes actuelles gagnées depuis le lundi 00h01

**Comment by LiseBorning** [comment]
[Uploading Challenges2024 (1).xlsx…]()

**Comment by briceandre** [comment]
C'est fait. Pour mettre le résultat d'une équipe, il faut mettre ||team_1||. L'ordre sera le même que celui du fichier excel d'inscription
