### ISSUE TITLE
Changements post inscriptions

### ISSUE THREAD

**Issue by LiseBorning** [briceandre/BorningChallenge#88]
- L'équipe 57 est à ajouter: Les Borneurs Planners
jean-michel.alfrena@alstomgroup.com Jean-Michel ALFRENA
gaoussou.cisse-ext@alstomgroup.com Gaoussou CISSE
maurine.dagneaux@alstomgroup.com Maurine DAGNEAUX
kylian.recourse-ext@alstomgroup.com Kylian RECOURSE
gilchrist-lewis.azagoh-kouadio-ext@alstomgroup.com Lewis AZAGOH-KOUADIO
clement.blanchard@alstomgroup.com Clément BLANCHARD

- La team 44 s'appelle Bornibar
- La team 50 s'appelle Nordics Express et a ajouté son image (team50.png)
- Roza Pocsai doit être supprimée de l'équipe 37 car elle est dans l'équipe 52
- La team 29 a ajouté sa photo team29.png
- La team 37 s'appelle désormais Last but not least et a ajouté sa photo team37.png

- L'équipe Federados 6000 se retrouve splittée en 6 (si j'ai bien suivi) avec chaque personne étant seule dans une équipe Federados 6001, Federados 6002, Federados 6003 etc,...  Donc les regrouper en une seule équipe Federados 6000

- Laurent Boileau voudrait être borneur solitaire sans équipe (il ne veut vraiment pas intégrer une équipe...)

**Comment by LiseBorning** [comment]
Les images sont sur le lien sharepoint https://alstomgroup.sharepoint.com/:f:/r/sites/BE_Borning_Challenge/Shared%20Documents/Inscription/Photos/[Teams_2024](https://alstomgroup.sharepoint.com/:f:/r/sites/BE_Borning_Challenge/Shared%20Documents/Inscription/Photos/Teams_2024?csf=1&web=1&e=nblxrJ)?csf=1&web=1&e=nblxrJ
As tu 27 images?

**Comment by LiseBorning** [comment]
Et Baudouin WELLENS voudrait être ajouté à l'équipe 22 Les Spiroux
baudouin.wellens-1@alstomgroup.com

**Comment by briceandre** [comment]
done
