### ISSUE TITLE
sélection d'un subset des challenges #perfo

### ISSUE THREAD

**Issue by briceandre** [briceandre/BorningChallenge#9]
choisir les challenges à garder : @OlivierDEVOSAlstom 
Adapter le site : @briceandre

**Comment by OlivierDEVOSAlstom** [comment]
voilà les défis à encoder pour les perfo
#perforun5 	Battre le précédent temps réalisé au défi #run5
#perforun10	Battre le précédent temps réalisé au défi #run10
#perforun13	Battre le précédent temps réalisé au défi #run13

#perfonatation300 	Battre le précédent temps réalisé au défi #natation300 
#perfonatation1000	Battre le précédent temps réalisé au défi #natation1000 
#perfonatation1500	Battre le précédent temps réalisé au défi #natation1500 

#perfobike10km 	Battre le précédent temps réalisé au défi #bike10km 
#perfobike20km 	Battre le précédent temps réalisé au défi #bike20km 
#perfobike35km 	Battre le précédent temps réalisé au défi #bike35km 

--> ne pas les afficher tout de suite, les libérer les 2 dernières semaines

**Comment by briceandre** [comment]
OK pour moi, je les ferai en même temps que la mise à jour de tous les défis.

Juste une question @OlivierDEVOSAlstom : on considère qu'à partir du moment où ils ont fait 1 seconde de mieux, c'est OK ? Ou on impose une progression "significative" ?

**Comment by OlivierDEVOSAlstom** [comment]
Ce sera 1 minute de mieux vu qu'on ne compte pas les secondes ;)
Mais oui c'est suffisant comme ça, sinon on va se retrouver à devoir justifier ce qu'est une "progression significative"

**Comment by briceandre** [comment]
Je peux pas juste me baser sur le temps : la distance ne sera pas forcément la même, vu qu'on peut valider un run5 avec un 7 bornes.
Je propose de faire en fonction de l'allure, mais faudrait mettre une marge min du coup.
Pour le run, je propose 10 ou 15 secondes de mieux au km. Pour les autres, j'ai pas trop d'idée

**Comment by briceandre** [comment]
@OlivierDEVOSAlstom  : pas sûr que tu as vu ma question... Je relance donc

**Comment by OlivierDEVOSAlstom** [comment]
Hello Brice,
J'avais vu la question mais j'avoue que ça demandait réflexion. Pour se baser sur l'allure aucun souci
Par contre je pense qu'on devrait mettre amélioration total de 30sec sur la course, 10sec sur la natation et 1min sur le vélo

Pour les plus grand sportif ce sera dur de gagner beaucoup de temps (donc 10sec au km c'est énorme) - après on pourra toujours au moment de l'ouverture de ces challenges de dire aux gens combien ils doivent gagner pour ne pas qu'ils prennent de risques de tout donner et se blesser

**Comment by briceandre** [comment]
Pour moi, il faut travailler sur l'allure : le type qui a encodé un challenge 5km en en faisant 7, ça va être easy de gagner 30 secondes si la 2e fois, il en cours que 5.

Si on prend ta proposition de 30 secondes sur la course, si c'est sur un 5km, ça correspond à un gain de 6s/km (au lieu des 15s/km que je proposais).

Pour les valeurs, je te laisse voir. Perso, ça dépend tellement : j'ai tapé le 5km avec une course relax avec mon fils. Gagner, 5s/km, ça va être easy.... Pour les autres sports, j'ai vraiment pas d'idée...
